// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace nanhdayhoc2024.Migrations
{
    [DbContext(typeof(LTQDD))]
    partial class LTQDDModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("nanh_dayhoc_2024.Models.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaLop");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("nanh_dayhoc_2024.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinHVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSinHVien");

                    b.ToTable("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
